"""
KeyMap Export Engine — Meta-Stamp V3

Generates platform-specific keyboard remapping scripts from a shortcut mapping.

Supported export formats:
  - autohotkey   → Windows AutoHotkey v2 script (.ahk)
  - karabiner    → macOS Karabiner-Elements JSON (.json)
  - keyboard_maestro → macOS Keyboard Maestro macro library (.kmmacros XML)
  - stream_deck  → Elgato Stream Deck profile JSON (.streamDeckProfile)
  - markdown     → Human-readable reference table (.md)
"""

import json
import re
from typing import Any


# ---------------------------------------------------------------------------
# Key normalisation helpers
# ---------------------------------------------------------------------------

# Map shortcut string tokens to AutoHotkey v2 notation
_AHK_MOD_MAP = {
    "Cmd":   "^",   # Ctrl on Windows (Cmd → Ctrl cross-platform)
    "Ctrl":  "^",
    "Opt":   "!",   # Alt
    "Alt":   "!",
    "Shift": "+",
    "Win":   "#",
}

_KARABINER_MOD_MAP = {
    "Cmd":   "command",
    "Ctrl":  "control",
    "Opt":   "option",
    "Alt":   "option",
    "Shift": "shift",
}

_KARABINER_KEY_MAP = {
    "Space":  "spacebar",
    "Return": "return_or_enter",
    "Enter":  "return_or_enter",
    "Delete": "delete_or_backspace",
    "Escape": "escape",
    "Tab":    "tab",
    "Left":   "left_arrow",
    "Right":  "right_arrow",
    "Up":     "up_arrow",
    "Down":   "down_arrow",
    "Home":   "home",
    "End":    "end",
    "Comma":  "comma",
    "Period": "period",
    "\\":     "backslash",
    "/":      "slash",
    "=":      "equal_sign",
    "-":      "hyphen",
    "`":      "grave_accent_and_tilde",
    "[":      "open_bracket",
    "]":      "close_bracket",
    ";":      "semicolon",
    "'":      "quote",
    "Num1":   "keypad_1",
    "Num2":   "keypad_2",
    "Num8":   "keypad_8",
    "Num9":   "keypad_9",
    "Num,":   "keypad_comma",
    "Num+":   "keypad_plus",
}


def _parse_shortcut(shortcut: str) -> tuple[list[str], str]:
    """Split 'Cmd+Shift+K' into (['Cmd', 'Shift'], 'K')."""
    if not shortcut:
        return [], ""
    parts = [p.strip() for p in shortcut.split("+")]
    modifiers = parts[:-1]
    key = parts[-1]
    return modifiers, key


def _to_ahk(shortcut: str) -> str:
    """Convert 'Cmd+Shift+K' to AutoHotkey v2 notation '^+k'."""
    if not shortcut or shortcut in ("None", "N/A"):
        return ""
    # Handle multi-key shortcuts like "Q / W" — take first
    shortcut = shortcut.split("/")[0].strip()
    mods, key = _parse_shortcut(shortcut)
    ahk_mods = "".join(_AHK_MOD_MAP.get(m, "") for m in mods)
    # Special keys
    special = {
        "Space": "Space", "Return": "Enter", "Enter": "Enter",
        "Delete": "Delete", "Escape": "Escape", "Tab": "Tab",
        "Left": "Left", "Right": "Right", "Up": "Up", "Down": "Down",
        "Home": "Home", "End": "End", "Comma": ",", "Period": ".",
        "F1": "F1", "F2": "F2", "F3": "F3", "F4": "F4",
        "F5": "F5", "F6": "F6", "F7": "F7", "F8": "F8",
        "F9": "F9", "F10": "F10", "F11": "F11", "F12": "F12",
        "Num1": "Numpad1", "Num2": "Numpad2",
        "Num8": "Numpad8", "Num9": "Numpad9",
    }
    ahk_key = special.get(key, key.lower() if len(key) == 1 else key)
    return f"{ahk_mods}{ahk_key}"


def _to_karabiner_key(key: str) -> str:
    """Convert a key name to Karabiner key_code."""
    if key in _KARABINER_KEY_MAP:
        return _KARABINER_KEY_MAP[key]
    if len(key) == 1:
        return key.lower()
    # Function keys
    if re.match(r"^F\d+$", key):
        return f"f{key[1:]}"
    return key.lower()


def _to_karabiner_mods(mods: list[str]) -> list[str]:
    return [_KARABINER_MOD_MAP[m] for m in mods if m in _KARABINER_MOD_MAP]


# ---------------------------------------------------------------------------
# Export: AutoHotkey v2
# ---------------------------------------------------------------------------

def export_autohotkey(
    mappings: list[dict],
    source_app: str,
    target_app: str,
    source_name: str,
    target_name: str,
) -> str:
    """Generate an AutoHotkey v2 script that remaps source shortcuts to target shortcuts."""
    lines = [
        f"; KeyMap — {source_name} → {target_name}",
        f"; Generated by Meta-Stamp KeyMap Engine",
        f"; This script remaps {source_name} muscle-memory onto {target_name}",
        f"; Only active when {target_name} is the focused window",
        "",
        "#Requires AutoHotkey v2.0",
        "#SingleInstance Force",
        "",
        f"; ============================================================",
        f"; Activate only when {target_name} is focused",
        f"; ============================================================",
        "",
    ]

    # Group by category
    categories: dict[str, list[dict]] = {}
    for m in mappings:
        if m["mapped"] and m["source_shortcut"] and m["target_shortcut"]:
            cat = m["category"]
            categories.setdefault(cat, []).append(m)

    # Determine window title filter (best-effort)
    window_titles = {
        "final_cut_pro": "Final Cut Pro",
        "premiere_pro": "Adobe Premiere Pro",
        "capcut": "CapCut",
        "davinci_resolve": "DaVinci Resolve",
        "pro_tools": "Pro Tools",
        "logic_pro": "Logic Pro",
    }
    win_title = window_titles.get(target_app, target_app)

    lines.append(f'#HotIf WinActive("{win_title}")')
    lines.append("")

    for cat, items in categories.items():
        lines.append(f"; --- {cat} ---")
        for m in items:
            src = _to_ahk(m["source_shortcut"])
            tgt = _to_ahk(m["target_shortcut"])
            if src and tgt and src != tgt:
                lines.append(f"{src}:: SendInput '{{{tgt}}}'  ; {m['label']}")
        lines.append("")

    lines.append("#HotIf  ; End context-sensitive block")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Export: Karabiner-Elements JSON
# ---------------------------------------------------------------------------

def export_karabiner(
    mappings: list[dict],
    source_app: str,
    target_app: str,
    source_name: str,
    target_name: str,
) -> str:
    """Generate a Karabiner-Elements complex_modifications JSON rule set."""
    rules = []

    for m in mappings:
        if not (m["mapped"] and m["source_shortcut"] and m["target_shortcut"]):
            continue
        src_str = m["source_shortcut"].split("/")[0].strip()
        tgt_str = m["target_shortcut"].split("/")[0].strip()
        if src_str == tgt_str:
            continue

        src_mods, src_key = _parse_shortcut(src_str)
        tgt_mods, tgt_key = _parse_shortcut(tgt_str)

        from_block: dict[str, Any] = {
            "key_code": _to_karabiner_key(src_key),
        }
        if src_mods:
            from_block["modifiers"] = {
                "mandatory": _to_karabiner_mods(src_mods),
                "optional": ["any"],
            }

        to_block: dict[str, Any] = {
            "key_code": _to_karabiner_key(tgt_key),
        }
        if tgt_mods:
            to_block["modifiers"] = _to_karabiner_mods(tgt_mods)

        # App-specific condition
        bundle_ids = {
            "final_cut_pro": "com.apple.FinalCut",
            "premiere_pro": "com.adobe.PremierePro",
            "capcut": "com.lemon.lvideo-mac",
            "davinci_resolve": "com.blackmagic-design.davinci-resolve",
            "pro_tools": "com.avid.ProTools",
            "logic_pro": "com.apple.logic10",
        }
        bundle_id = bundle_ids.get(target_app, "")
        conditions = []
        if bundle_id:
            conditions.append({
                "type": "frontmost_application_if",
                "bundle_identifiers": [bundle_id],
            })

        rule: dict[str, Any] = {
            "description": f"{source_name} → {target_name}: {m['label']}",
            "manipulators": [
                {
                    "type": "basic",
                    "from": from_block,
                    "to": [to_block],
                    **({"conditions": conditions} if conditions else {}),
                }
            ],
        }
        rules.append(rule)

    output = {
        "title": f"KeyMap: {source_name} → {target_name}",
        "rules": rules,
    }
    return json.dumps(output, indent=2)


# ---------------------------------------------------------------------------
# Export: Keyboard Maestro (XML macro library)
# ---------------------------------------------------------------------------

def export_keyboard_maestro(
    mappings: list[dict],
    source_app: str,
    target_app: str,
    source_name: str,
    target_name: str,
) -> str:
    """Generate a Keyboard Maestro macro library XML."""
    import uuid

    app_bundle_ids = {
        "final_cut_pro": "com.apple.FinalCut",
        "premiere_pro": "com.adobe.PremierePro",
        "capcut": "com.lemon.lvideo-mac",
        "davinci_resolve": "com.blackmagic-design.davinci-resolve",
        "pro_tools": "com.avid.ProTools",
        "logic_pro": "com.apple.logic10",
    }
    bundle_id = app_bundle_ids.get(target_app, "")
    group_uid = str(uuid.uuid4()).upper()

    macros_xml = []
    for m in mappings:
        if not (m["mapped"] and m["source_shortcut"] and m["target_shortcut"]):
            continue
        src_str = m["source_shortcut"].split("/")[0].strip()
        tgt_str = m["target_shortcut"].split("/")[0].strip()
        if src_str == tgt_str:
            continue

        macro_uid = str(uuid.uuid4()).upper()
        # Build trigger key string for KM (simplified)
        src_mods, src_key = _parse_shortcut(src_str)
        km_mods = ""
        if "Cmd" in src_mods:   km_mods += "@"
        if "Shift" in src_mods: km_mods += "$"
        if "Opt" in src_mods:   km_mods += "~"
        if "Ctrl" in src_mods:  km_mods += "^"

        # Target keystroke
        tgt_mods_list, tgt_key = _parse_shortcut(tgt_str)
        tgt_km_mods = ""
        if "Cmd" in tgt_mods_list:   tgt_km_mods += "@"
        if "Shift" in tgt_mods_list: tgt_km_mods += "$"
        if "Opt" in tgt_mods_list:   tgt_km_mods += "~"
        if "Ctrl" in tgt_mods_list:  tgt_km_mods += "^"

        macros_xml.append(f"""        <dict>
            <key>Actions</key>
            <array>
                <dict>
                    <key>Action</key>
                    <string>TypeKeystroke</string>
                    <key>Keystroke</key>
                    <dict>
                        <key>Key</key>
                        <string>{tgt_key.lower()}</string>
                        <key>Modifiers</key>
                        <string>{tgt_km_mods}</string>
                    </dict>
                </dict>
            </array>
            <key>Name</key>
            <string>{m['label']} ({source_name} → {target_name})</string>
            <key>Trigger</key>
            <dict>
                <key>Key</key>
                <string>{src_key.lower()}</string>
                <key>Modifiers</key>
                <string>{km_mods}</string>
                <key>Type</key>
                <string>HotKey</string>
            </dict>
            <key>UID</key>
            <string>{macro_uid}</string>
        </dict>""")

    app_condition = ""
    if bundle_id:
        app_condition = f"""        <key>Application</key>
        <dict>
            <key>BundleIdentifier</key>
            <string>{bundle_id}</string>
        </dict>"""

    xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
    <dict>
        <key>Macros</key>
        <array>
{"".join(macros_xml)}
        </array>
        <key>Name</key>
        <string>KeyMap: {source_name} → {target_name}</string>
        <key>UID</key>
        <string>{group_uid}</string>
{app_condition}
    </dict>
</array>
</plist>"""
    return xml


# ---------------------------------------------------------------------------
# Export: Stream Deck Profile JSON
# ---------------------------------------------------------------------------

def export_stream_deck(
    mappings: list[dict],
    source_app: str,
    target_app: str,
    source_name: str,
    target_name: str,
) -> str:
    """Generate an Elgato Stream Deck profile JSON (15-key layout)."""
    import uuid

    profile_id = str(uuid.uuid4()).upper()
    actions = {}

    mapped_items = [
        m for m in mappings
        if m["mapped"] and m["source_shortcut"] and m["target_shortcut"]
    ][:15]  # Stream Deck MK.2 has 15 keys

    for i, m in enumerate(mapped_items):
        tgt_str = m["target_shortcut"].split("/")[0].strip()
        tgt_mods, tgt_key = _parse_shortcut(tgt_str)

        # Build hotkey string for Stream Deck
        sd_mods = []
        if "Cmd" in tgt_mods:   sd_mods.append("command")
        if "Shift" in tgt_mods: sd_mods.append("shift")
        if "Opt" in tgt_mods:   sd_mods.append("option")
        if "Ctrl" in tgt_mods:  sd_mods.append("ctrl")

        actions[str(i)] = {
            "UUID": "com.elgato.streamdeck.system.hotkey",
            "Settings": {
                "HotKey": {
                    "KeyCode": tgt_key.lower(),
                    "Modifiers": sd_mods,
                },
                "Title": m["label"][:20],
            },
            "State": 0,
            "States": [{"Title": m["label"][:20]}],
        }

    profile = {
        "Actions": actions,
        "AppIdentifier": {
            "Mac": f"com.example.{target_app}",
            "Windows": f"{target_app}.exe",
        },
        "DeviceModel": "Stream Deck MK.2",
        "Name": f"KeyMap: {source_name} → {target_name}",
        "ProfileUUID": profile_id,
        "Version": "1.0",
    }
    return json.dumps(profile, indent=2)


# ---------------------------------------------------------------------------
# Export: Markdown reference table
# ---------------------------------------------------------------------------

def export_markdown(
    mappings: list[dict],
    source_app: str,
    target_app: str,
    source_name: str,
    target_name: str,
    platform: str = "mac",
) -> str:
    """Generate a human-readable Markdown shortcut reference table."""
    lines = [
        f"# KeyMap: {source_name} → {target_name}",
        f"",
        f"*Platform: {platform.title()} | Generated by Meta-Stamp KeyMap Engine*",
        f"",
        f"This table maps your {source_name} muscle-memory onto {target_name}.",
        f"",
    ]

    # Group by category
    categories: dict[str, list[dict]] = {}
    for m in mappings:
        cat = m["category"]
        categories.setdefault(cat, []).append(m)

    for cat, items in sorted(categories.items()):
        lines.append(f"## {cat}")
        lines.append("")
        lines.append(f"| Action | {source_name} Shortcut | {target_name} Shortcut | Status |")
        lines.append("|--------|------------------------|------------------------|--------|")
        for m in items:
            src = m["source_shortcut"] or "—"
            tgt = m["target_shortcut"] or "—"
            status = "✅ Mapped" if m["mapped"] else "⚠️ No equivalent"
            lines.append(f"| {m['label']} | `{src}` | `{tgt}` | {status} |")
        lines.append("")

    # Summary
    total = len(mappings)
    mapped = sum(1 for m in mappings if m["mapped"])
    lines.append(f"---")
    lines.append(f"**Coverage:** {mapped}/{total} shortcuts mapped ({round(mapped/total*100)}%)")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Master export dispatcher
# ---------------------------------------------------------------------------

def export_mapping(
    mappings: list[dict],
    source_app: str,
    target_app: str,
    source_name: str,
    target_name: str,
    format: str,
    platform: str = "mac",
) -> tuple[str, str, str]:
    """
    Dispatch to the correct exporter.

    Returns: (content: str, filename: str, mime_type: str)
    """
    safe_src = source_app.replace("_", "-")
    safe_tgt = target_app.replace("_", "-")

    if format == "autohotkey":
        content = export_autohotkey(mappings, source_app, target_app, source_name, target_name)
        return content, f"keymap-{safe_src}-to-{safe_tgt}.ahk", "text/plain"

    elif format == "karabiner":
        content = export_karabiner(mappings, source_app, target_app, source_name, target_name)
        return content, f"keymap-{safe_src}-to-{safe_tgt}.json", "application/json"

    elif format == "keyboard_maestro":
        content = export_keyboard_maestro(mappings, source_app, target_app, source_name, target_name)
        return content, f"keymap-{safe_src}-to-{safe_tgt}.kmmacros", "application/xml"

    elif format == "stream_deck":
        content = export_stream_deck(mappings, source_app, target_app, source_name, target_name)
        return content, f"keymap-{safe_src}-to-{safe_tgt}.streamDeckProfile", "application/json"

    elif format == "markdown":
        content = export_markdown(mappings, source_app, target_app, source_name, target_name, platform)
        return content, f"keymap-{safe_src}-to-{safe_tgt}.md", "text/markdown"

    else:
        raise ValueError(f"Unsupported export format: {format}")
